github: [metadata]
encoding: UTF-8
kramdown:
 input: GFM
 hard_wrap: false
sass:
  sass_dir: _sass
  style: compact
  sourcemap: true
future: true
jailed: false
gfm_quirks: paragraph_end
exclude: [leohuber_github_io.iml, run_locally.sh, Gemfile, Gemfile.lock]
collections_dir: collections
collections:
  cheatsheets:
    output: true