github: [metadata]
encoding: UTF-8
kramdown:
 input: GFM
 hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
exclude: [leohuber_github_io.iml, run_locally.sh]
remote_theme: leohuber/jekyll-theme-mayla